export { createSphereVertices } from './sphere.js'
export { createCylinderVertices } from './cylinder.js'
export { createPyramidVertices } from './pyramid.js'
export { createRectangleVertices } from './rectangle.js'
export { createCubeVertices} from './cube.js' 